urls.py
from django.conf.urls.defaults import *
from django.conf import settings

urlpatterns = patterns('',
	(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT }),
	(r'^$','plan.views.index'),
	(r'^department/$','plan.views.form_department'),
	(r'^department/(?P<id>\d+)$','plan.views.department'),
	(r'^attribute/$','plan.views.form_attribute'),
	(r'^attribute/(?P<id>\d+)$','plan.views.attribute'),
	(r'^degree/$','plan.views.form_degree'),
	(r'^degree/(?P<id>\d+)$','plan.views.degree'),
	(r'^course/$','plan.views.form_course'),
	(r'^course/(?P<id>\d+)$','plan.views.course'),
	(r'^period_day/$','plan.views.form_period_day'),
	(r'^period_day/(?P<id>\d+)$','plan.views.period_day'),
	(r'^period/$','plan.views.form_period'),
	(r'^period/(?P<id>\d+)$','plan.views.period'),
	(r'^offering/$','plan.views.form_offering'),
	(r'^offering/(?P<id>\d+)$','plan.views.offering'),
	(r'^student/$','plan.views.form_student'),
	(r'^student/(?P<id>\d+)$','plan.views.student'),
	(r'^asp/$','plan.views.asp'),
	(r'^write_asp/(?P<s>\d+)/(?P<min>\d+)/(?P<max>\d+)/$','plan.views.write_asp'),
	(r'^status/$', 'plan.views.status'),
	(r'^view_status/$', 'plan.views.view_status'),
	(r'^results/$', 'plan.views.results'),
	(r'^results/(?P<s>\d+)/(?P<p>\d+)$', 'plan.views.results_paged'),
	(r'^schedules/(?P<s>\d+)/(?P<p>\d+)/$', 'plan.views.schedule'),
	(r'^plan/$', 'plan.views.plan'),
	(r'^calendar/(?P<s>\d+)$', 'plan.views.calendar'),
	(r'^num_schedules/$', 'plan.views.num_schedules'),
)

plan/models.py
from django.db import models
from django.forms import ModelForm, ModelMultipleChoiceField
import os

OFILE = 'asp/.tmp/asp'

class Department(models.Model):
	name = models.CharField(max_length=500)
	abbreviation = models.CharField(max_length=4)
	
	class Meta:
		ordering = ['name','abbreviation']
	
	def asp(self):
	    return 'dept(dept%d).\n' % self.id
	
	def __str__(self):
		return self.name
	
	def __unicode__(self):
		return self.name
	

class Attribute(models.Model):
	name = models.CharField(max_length=500)
	
	class Meta:
		ordering = ['name']
	
	def asp(self):
	    return 'attr(attr%d).\n' % self.id
	
	def __str__(self):
		return self.name
	
	def __unicode__(self):
		return self.name
	

class Degree(models.Model):
	name = models.CharField(max_length=500)
	description = models.TextField()
	department = models.ForeignKey('Department')
	required_courses = models.ManyToManyField('Course')
	
	class Meta:
		ordering = ['name']
	
	def asp(self):
	    asp = 'degree(degree%d).\n' % self.id
	    asp += 'deg_in_dept(degree%d, dept%d).\n' % (self.id, self.department.id)
	    for c in self.required_courses.all():
	        asp += 'deg_req(degree%d, course%d).\n' % (self.id, c.id)
	    for a in self.required_attrs.all():
	        asp += 'deg_attr_req(degree%d, attr%d, %d).\n' % (self.id, a.attribute.id, a.hours)
	    return asp
	
	def __str__(self):
		return self.name
	
	def __unicode__(self):
		return self.name
	

class AttributeRequirement(models.Model):
    attribute = models.ForeignKey('Attribute')
    hours = models.IntegerField()
    degrees = models.ManyToManyField('Degree', related_name='required_attrs')
    
    class Meta:
        ordering = ['attribute__name','hours']
    
    def met_by(self):
        return self.attribute.course_set()
    
    def __str__(self):
        return str(self.hours) + ' / ' + str(self.attribute)
    
    def __unicode__(self):
        return str(self.hours) + ' / ' + str(self.attribute)
    

class Course(models.Model):
	department = models.ForeignKey('Department')
	number = models.CharField(max_length=4)
	name = models.CharField(max_length=100)	
	hours = models.IntegerField()
	meets = models.ManyToManyField('Attribute', blank=True)
	prerequisites = models.ManyToManyField('Course', related_name='preq', blank=True, symmetrical=False)
	corequisites = models.ManyToManyField('Course', related_name='creq', blank=True, symmetrical=True)
	
	class Meta:
		ordering = ['department__name','number']
	
	def asp(self):
	    asp = 'course(course%d).\n' % self.id
	    asp += 'course_number(course%d,%s).\n' % (self.id, self.number)
	    asp += 'in_dept(course%d, dept%d).\n' % (self.id, self.department.id)
	    asp += 'course_hours(course%d, %d).\n' % (self.id, self.hours)
	    for a in self.meets.all():
	        asp += 'meets(course%d, attr%d).\n' % (self.id, a.id)
	    for r in self.prerequisites.all():
	        asp += 'preq(course%d, course%d).\n' % (r.id, self.id)
	    for q in self.corequisites.all():
	        asp += 'creq(course%d, course%d).\n' % (self.id, q.id)
	    return asp
	
	def __str__(self):
		return self.department.abbreviation + str(self.number)
	
	def __unicode__(self):
		return self.department.abbreviation + str(self.number)
	

class PeriodDay(models.Model):
	PERIOD_DAYS = (
		('1','Monday'),
		('2','Tuesday'),
		('3','Wednesday'),
		('4','Thursday'),
		('5','Friday'),
		('6','Saturday'),
		('7','Sunday')
	)
	
	day = models.IntegerField(choices=PERIOD_DAYS)
	
	class Meta:
		ordering = ['day']
	
	def courses(self):
	    return Course.objects.filter(offering__period__day__id=self.id).distinct()
	
	def full_str(self):
		return str(self.PERIOD_DAYS[self.day-1][1])
	
	def abbr_str(self):
		if self.day not in (4,7):
			return str(self.PERIOD_DAYS[self.day-1][1][0])
		else:
			if self.day == 4:
				return 'R'
			else:
				return 'U'	
	
	def __str__(self):
		return self.full_str()
	
	def __unicode__(self):
		return self.full_str()
	

class Period(models.Model):
	starts = models.TimeField()
	ends = models.TimeField()
	day = models.ManyToManyField('PeriodDay')
	
	class Meta:
		ordering = ['starts','ends']
	
	def asp(self):
	    asp = 'period(period%d).\n' % self.id
	    asp += 'starts(period%d, %s).\n' % (self.id, str(self.starts.hour) + self.starts.strftime('%M'))
	    asp += 'ends(period%d, %s).\n' % (self.id, str(self.ends.hour) + self.ends.strftime('%M'))
	    for d in self.day.all():
	        asp += 'day(period%d, %d).\n' % (self.id, d.day)
	    return asp
	
	def __str__(self):
		name = ""
		name += self.starts.strftime("%H%M") + "-" + self.ends.strftime("%H%M") + " "
		for d in self.day.all():
			name += d.abbr_str()
		return name
	
	def __unicode__(self):
		name = ""
		name += self.starts.strftime("%H%M") + "-" + self.ends.strftime("%H%M") + " "		
		for d in self.day.all():
			name += d.abbr_str()
		return name

class Offering(models.Model):
	course = models.ForeignKey('Course')
	period = models.ForeignKey('Period')
	section = models.CharField(max_length=3)
	
	class Meta:
		ordering = ['course','section']
	
	def asp(self):
	    asp = 'offering(offering%d).\n' % self.id
	    asp += 'offer_course(offering%d, course%d).\n' % (self.id, self.course.id)
	    asp += 'offer_section(offering%d, s%s).\n' % (self.id, self.section)
	    asp += 'offer_pd(offering%d, period%d).\n' % (self.id, self.period.id)
	    return asp
	
	def __str__(self):
		return str(self.course) + "-" + str(self.section)
		
	def __unicode__(self):
		return str(self.course) + "-" + str(self.section)
	

class Student(models.Model):
	first_name = models.CharField(max_length = 500)
	last_name = models.CharField(max_length = 500)
	email = models.EmailField(max_length = 250)
	degree_plan = models.ForeignKey('Degree')
	taken = models.ManyToManyField('Course')
	
	class Meta:
		ordering = ['last_name','first_name','email']
	
	def asp(self):
	    asp = 'student(student%d).\n' % self.id
	    asp += 'selected(student%d).\n' % self.id
	    asp += 'student_deg(student%d, degree%d).\n' % (self.id, self.degree_plan.id)
	    for c in self.taken.all():
	        asp += 'taken(student%d, course%d).\n' % (self.id, c.id)
	    return asp
    
	def __str__(self):
		return self.first_name + " " + self.last_name + " (" + self.email + ")"
	
	def __unicode__(self):
		return self.first_name + " " + self.last_name + " (" + self.email + ")"
	

class Schedule(models.Model):
    student = models.ForeignKey('Student')
    offerings = models.ManyToManyField('Offering',symmetrical=False)
    hours = models.IntegerField()
    
    class Meta:
        ordering = ['hours',]
    
    
    def offer_list(self):
        return list(self.offerings.all())

    def __str__(self):
        s = ' '
        for o in self.offerings.all():
            s += str(o) + ' '
        return s
    
    def __unicode__(self):
        s = ' '
        for o in self.offerings.all():
            s += str(o) + ' '
        return s
    

plan/forms.py
from django.db import models
from django.forms import ModelForm
from plan.models import *

class DepartmentForm(ModelForm):
	class Meta:
		model = Department
	

class AttributeForm(ModelForm):
	class Meta:
		model = Attribute
	

class DegreeForm(ModelForm):
	class Meta:
		model = Degree
	

class CourseForm(ModelForm):
	class Meta:
		model = Course
	

class PeriodDayForm(ModelForm):
	class Meta:
		model = PeriodDay
	

class PeriodForm(ModelForm):
	class Meta:
		model = Period
	

class OfferingForm(ModelForm):
	class Meta:
		model = Offering
	

class StudentForm(ModelForm):
	class Meta:
		model = Student
	

plan/views.py
import os
from plan import *
from plan.forms import *
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import logout_then_login, login
from django.contrib.auth.decorators import login_required, user_passes_test
from django.template import RequestContext

def log(msg):
    from datetime import datetime    
    f = open("log.log","a")
    msg = "%s\t%s\n" % (datetime.now(),msg)
    f.write(msg)
    f.close()

def index(request):
    return render_to_response('index.html', {
        'PAGE_TITLE' : 'welcome',
    })

def form(request,otype,title):
    if request.method == 'POST':
        form = otype(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = otype()

    items = otype.Meta.model.objects.all()
    return render_to_response('form.html', {
        'PAGE_TITLE' : title,
        'form' : form,
        'items' : items,
    })

def form_department(request):
    return form(request,DepartmentForm,'Department')

def form_attribute(request):
    return form(request,AttributeForm,'Attribute')

def form_degree(request):
    return form(request,DegreeForm,'Degree')

def form_course(request):
    return form(request,CourseForm,'Course')

def form_period_day(request):
    return form(request,PeriodDayForm,'Period Day')

def form_period(request):
    return form(request,PeriodForm,'Period')

def form_offering(request):
    return form(request,OfferingForm,'Offering')

def form_student(request):
    return form(request,StudentForm,'Student')

def view_item(request,otype,id,template):
    item = otype.objects.get(id=id)
    return render_to_response(template, {
        'PAGE_TITLE' : str(item),
        'item' : item,
    })

def department(request,id):
    return view_item(request,Department,id,'view_department.html')

def attribute(request,id):
    return view_item(request,Attribute,id,'view_attribute.html')

def degree(request,id):
    return view_item(request,Degree,id,'view_degree.html')

def course(request,id):
    return view_item(request,Course,id,'view_course.html')

def period_day(request,id):
    return view_item(request,PeriodDay,id,'view_period_day.html')

def period(request,id):
    return view_item(request,Period,id,'view_period.html')

def offering(request,id):
    return view_item(request,Offering,id,'view_offering.html')

def student(request,id):
    return view_item(request,Student,id,'view_student.html')

def asp(request):
    hmin = 3
    hmax = 21
    try:
        hmin = request.GET['hmin']
        hmax = request.GET['hmax']
    except:
        pass
    depts = Department.objects.all().order_by('id')
    attrs = Attribute.objects.all().order_by('id')
    courses = Course.objects.all().order_by('id')
    degrees = Degree.objects.all().order_by('id')
    periods = Period.objects.all().order_by('id')
    offerings = Offering.objects.all().order_by('id')
    students = Student.objects.all().order_by('id')
    return render_to_response('asp.html', {
        'PAGE_TITLE' : 'ASP Atoms',
        'depts' : depts,
        'attrs' : attrs,
        'courses' : courses,
        'degrees' : degrees,
        'periods' : periods,
        'offerings' : offerings,
        'students' : students,
        'hmin' : hmin,
        'hmax' : hmax,
    })
    
def write_asp(request,s,min,max):
    from django.http import HttpResponse
    
    OFILE = 'asp/.tmp/asp'
    RESULTS = 'asp/.tmp/results'
    
    os.system('rm' + RESULTS)
    
    student = Student.objects.get(id=s)
    f = open(OFILE,'a')    
    f.write('#hide.\n#show registered/5, total_hours/1.\n')
    f.write('#const hmin = %s.  %% min hours\n#const hmax = %s. %% max hours\n' % (min,max))    
    os.system('cat asp/prog.lp > ' + OFILE)
    f.write('\n\n')
    for d in Department.objects.all():
        f.write(d.asp())
    for a in Attribute.objects.all():
        f.write(a.asp())
    for c in Course.objects.all():
        f.write(c.asp())
    for g in Degree.objects.all():
        f.write(g.asp())
    for p in Period.objects.all():
        f.write(p.asp())
    for o in Offering.objects.all():
        f.write(o.asp())
    f.write(student.asp())
    f.close()
    
    os.system('gringo ' + OFILE + '| clasp --asp09 -n0 1>' + RESULTS + ' ; ./test_shell.py parse_asp &')
        
    return HttpResponseRedirect('/schedules/%d/1' % int(s))


def view_status(request):
    return render_to_response('view_status.html')

def status(request):
    from django.http import HttpResponse
    try:
        f = open('log.log','rx')
        s = f.read()
        f.close()
        return HttpResponse(s,mimetype='text/plain')
    except:
        return HttpResponse('Log not found.',mimetype='text/plain')

def results(request):
    schedules = Schedule.objects.all()
    return render_to_response('results.html', {
        'PAGE_TITLE' : 'Results',
        'schedules' : schedules,
    })

def results_paged(request,s,p):
    RESULTS_PER_PAGE = 50
    
    stu = Student.objects.get(id=s)
    schedules = Schedule.objects.get(student=stu)
    total = schedules.offerings.count()
    start = (int(p)-1)*RESULTS_PER_PAGE
    end = int(p)*RESULTS_PER_PAGE
    scheds = list(schedules)[start:end]
    start += 1
    msg = "Viewing results %d through " % start
    if end > total:
        msg += str(total)
    else:
        msg += str(end)
    msg += " of %d." % total
    
    maxpage = total/RESULTS_PER_PAGE
    if total % RESULTS_PER_PAGE > 0:
        maxpage += 1
    
    pages = range(1,maxpage + 1)
    
    return render_to_response('results_paged.html', {
        'PAGE_TITLE' : 'Results',
        'schedules' : scheds,
        'student' : stu,
        'start' : start,
        'end' : end,
        'total' : total,
        'msg' : msg,
        'pages' : pages,
        's' : s,
        'p' : p,
    })

def schedule(request,s,p):
    RPP = 50
    student = Student.objects.get(id=s)
    scheds = Schedule.objects.filter(student=student)
    total = len(scheds)
    
    start = (int(p)-1)*RPP
    end = int(p)*RPP
    scheds = scheds[start:end]
    start += 1
    msg = "Viewing results %d through " % start
    if end > total:
        msg += str(total)
    else:
        msg += str(end)
    
    maxpage = total / RPP 
    if total % RPP > 0:
        maxpage += 1
    
    pages = range(1,maxpage + 1)
    
    return render_to_response('schedules.html', {
        'PAGE_TITLE' : 'Schedules',
        'student' : student,
        'scheds' : scheds,
        'total' : total,
        'start' : start,
        'end' : end,
        'pages' : pages,
        'msg' : msg,
        'p' : int(p),
        's' : int(s),
    })

def plan(request):
    if request.method == "POST":
        student = request.POST['student']
        hmin = request.POST['hmin']
        hmax = request.POST['hmax']
        return write_asp(request,student,hmin,hmax)
        
    return render_to_response('plan.html', {
        'students' : Student.objects.all(),
    })

def calendar(request,s):
    sched = Schedule.objects.get(id=s)
    days = PeriodDay.objects.all()[0:5]
    hours = []
    for i in range(8,24):
        hours.append("%s:00" % i)
        hours.append("%s:30" % i)
    
    return render_to_response('calendar.html', {
        'PAGE_TITLE' : 'Calendar',
        'sched' : sched,
        'hours' : hours,
        'days' : days,
    })

def num_schedules(request):
    from django.http import HttpResponse
    return HttpResponse(Schedule.objects.count(),mimetype='text/plain')

templates/asp.html
{% extends "master.html" %}

{% block content %}
	<h1>{{ PAGE_TITLE }}</h1>
	<form id="hour_limits" method="get">
	    <p><b>Min hours:</b> <input type="text" id="hmin" name="hmin" value="{{ hmin }}"></p>
	    <p><b>Max hours:</b> <input type="text" id="hmax" name="hmax" value="{{ hmax }}"></p>	    
	    <input type="submit" value="Update">
    </form>
	<form id="write_code" method="post" action="/write_asp/">
    <input type="submit" value="Write to file" />	    
	<textarea readonly class="code" id="code" name="code">% input file for ASP planner
% generated {% now "r" %}

% ========== 
% = output = 
% ========== 
#hide.
#show registered/5.

% ===============
% = constraints =
% ===============
#const hmin = {{ hmin }}.  % min hours
#const hmax = {{ hmax }}. % max hours
		
% =============== 
% = departments = 
% =============== 
{% for dept in depts %}dept(dept{{ dept.id }}).
{% endfor %}
% ============== 
% = attributes = 
% ============== 
{% for a in attrs %}attr(attr{{ a.id }}).
{% endfor %}
% =========== 
% = courses = 
% =========== 
{% for c in courses %}course(course{{ c.id }}).
in_dept(course{{ c.id }}, dept{{ c.department.id }}).
course_hours(course{{ c.id }}, {{ c.hours }}).{% for a in c.meets.all %}
meets(course{{ c.id }}, attr{{ a.id }}).{% endfor %}{% for r in c.prerequisites.all %}
preq(course{{ r.id }}, course{{ c.id }}).{% endfor %}{% for o in c.corequisites.all %}
creq(course{{ c.id }}, course{{ o.id }}).{% endfor %}
{% endfor %}
% =========== 
% = degrees = 
% =========== 
{% for d in degrees %}degree(degree{{ d.id }}).
deg_in_dept(degree{{ d.id }}, dept{{ d.department.id }}).
{% for c in d.required_courses.all %}deg_req(degree{{ d.id }}, course{{ c.id }}).
{% endfor %}{% endfor %}
% ============ 
% = students = 
% ============ 
{% for s in students %}student(student{{ s.id }}).
student_deg(student{{ s.id }}, degree{{ s.degree_plan.id }}).{% if s.selected %}
selected(student{{ s.id }}).{% endif %}{% for c in s.taken.all %}
taken(student{{ s.id }},course{{ c.id }}).{% endfor %}
{% endfor %}
% =========== 
% = periods = 
% =========== 
{% for p in periods %}period(period{{ p.id }}).
starts(period{{ p.id }}, {{ p.starts|time:"Gi" }}).
ends(period{{ p.id }}, {{ p.ends|time:"Gi" }}).
{% for d in p.day.all %}day(period{{ p.id }}, {{ d.day }}).
{% endfor %}{% endfor %}
% ============= 
% = offerings = 
% ============= 
{% for o in offerings %}offering(offering{{ o.id }}).
offer_course(offering{{ o.id }}, course{{ o.course.id }}).
offer_section(offering{{ o.id }}, s{{ o.section }}).
offer_pd(offering{{ o.id }}, period{{ o.period.id }}).
{% endfor %}
</textarea>
<input type="submit" value="Write to file" />
</form>
<h2>Status</h2>
<script type="text/javascript" src="http://prototypejs.org/assets/2009/8/31/prototype.js"></script>
<script type="text/javascript">
new Ajax.PeriodicalUpdater('status','/status', {
   method: 'get',
   frequency: .5,
   decay: 0, 
});
</script>
<textarea readonly class="code" id="status" name="status" onChange="document.getElementById('status').scrollTop=document.getElementById('status').scrollHeight;"></textarea>
{% endblock %}

templates/calendar.html
{% extends "master.html" %}

{% block content %}
    <h1>{{ PAGE_TITLE }}</h1>
    <h3>Viewing schedule {{ sched.id }} for {{ sched.student.first_name}} {{ sched.student.last_name }} with {{ sched.hours }} total hours.</h3>
    <table class="calendar normal_th">
        <thead>
            <th></th>
            {% for d in days %}
                <th>{{ d }}</th>
            {% endfor %}
        </thead>
        <tbody>
            {% for h in hours %}
            <tr><th>{{ h }}</th>
            {% for d in days %}
            <td>
            {% for o in sched.offerings.all %}
            {% if d in o.period.day.all and o.period.starts|time:"G:i" <= h and o.period.ends|time:"G:i" > h %}
            <a href="/offering/{{ o.id }}">{{ o }}</a>
            {% endif %}
            {% endfor %}
            </td>
            {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/form.html
{% extends "master.html" %}

{% block content %}
	<form method="POST">
		<table>
		{% for field in form %}
			<tr><th>{{ field.label }}</th><td>{{ field }}</td></tr>
		{% endfor %}
			<tr><td colspan="2"><input type="submit"></td></tr>
		</table>
	</form>
	<ul class="items">
	{% for item in items %}
		<li><a href="{{ item.id }}">{{ item }}</a></li>
	{% endfor %}
	</ul>
{% endblock %}

templates/index.html
{% extends "master.html" %}

{% block content %}
<ul class="items">
	<li><a href="/department/">Department</a></li>
	<li><a href="/attribute/">Attribute</a></li>
	<li><a href="/degree/">Degree</a></li>
	<li><a href="/course/">Course</a></li>
	<li><a href="/period_day/">Period Day</a></li>
	<li><a href="/period/">Period</a></li>
	<li><a href="/offering/">Offering</a></li>
	<li><a href="/student/">Student</a></li>
</ul>
{% endblock %}

templates/master.html
<html>
	<head>
		<title>planner | {{ PAGE_TITLE }}</title>
		<link rel="stylesheet" href="/media/master.css" type="text/css">
	</head>
	<body>
		<div id="nav" class="wrapper">
			{% include "nav.html" %}
		</div>
		<div id="content" class="wrapper">
			{% block content %}{% endblock %}
		</div>
		<div id="footer" class="wrapper">
			Copyright &copy; Glen R. Hunt. All Rights Reserved.
		</div>
	</body>
</html>

templates/nav.html
<ul>
	<li><a href="/asp/">ASP</a></li>
	<li><a href="/results/">ASP Results</a></li>
	<li><a href="/department/">Department</a></li>
	<li><a href="/attribute/">Attribute</a></li>
	<li><a href="/degree/">Degree</a></li>
	<li><a href="/course/">Course</a></li>
	<li><a href="/period_day/">Period Day</a></li>
	<li><a href="/period/">Period</a></li>
	<li><a href="/offering/">Offering</a></li>
	<li><a href="/student/">Student</a></li>
</ul>

templates/plan.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html>
    <head>
        <title>Plan</title>
        <link rel="stylesheet" href="http://glenrhunt.com/reset" type="text/css">
        <link rel="stylesheet" href="/media/master2.css" type="text/css">
    </head>
    <body>
        <div id="wrapper">
            <h1>Plan Your Schedule.</h1>
            <form method="post">
                <h2>Select a student.</h2>
                {% if students %}
                <select id="student" name="student">
                {% for s in students %}
                    <option value="{{ s.id }}">{{ s }}</option>
                {% endfor %}
                </select>
                {% endif %}
                <h2>Select hour constraints.</h2>
                <table class="form">
                    <thead><tr><th>Min</th><th>Max</th></tr></thead>
                    <tbody><tr><td><input type="text" class="len3" maxlength="3" name="hmin" id="hmin" value="3"></td>
                        <td><input type="text" class="len3" maxlength="3" name="hmax" id="hmax" value="21"></td></tr></tbody>
                </table>
                <input type="submit" value="Calculate Schedules">
            </form>
        </div>
    </body>
</html>

templates/results_paged.html
{% extends "master.html" %}

{% block content %}
    <h1>{{ PAGE_TITLE }}</h1>
    <h2>{{ student }}</h2>
    <pre>{{ scheds }}</pre>
{% endblock %}

templates/view_department.html
{% extends "master.html" %}

{% block content %}
	<h1>{{ item }}</h1>
	<table>
		<tr><th>Name</th><td>{{ item.name }}</td></tr>
		<tr><th>Abbreviation</th><td>{{ item.abbreviation }}</td></tr>
		<tr><th>Courses</th><td>
		{% if item.course_set.all %}
			<ul class="items">
			{% for c in item.course_set.all %}
				<li><a href="/course/{{ c.id }}">{{ c }}</a></li>
			{% endfor %}
			</ul>
		{% else %}
			No courses listed for this department.
		{% endif %}
		</td></tr>
		<tr><th>Degrees</th><td>
		{% if item.degree_set.all %}
			<ul class="items">
			{% for d in item.degree_set.all %}
				<li><a href="/degree/{{ d.id }}">{{ d }}</a></li>
			{% endfor %}
			</ul>
		{% else %}
		No degrees listed for this department.
		{% endif %}
		</td></tr>
		<tr><th>ASP</th><td><pre>{{ item.asp }}</pre></td></tr>
	</table>
{% endblock %}

templates/view_period.html
{% extends "master.html" %}

{% block content %}
	<h1>{{ item }}</h1>
	<table>
		<tr><th>Starts</th><td>{{ item.starts }}</td></tr>
		<tr><th>Ends</th><td>{{ item.ends }}</td></tr>
		<tr><th>Days</th><td>
		{% if item.day.all %}
			<ul class="items">
			{% for d in item.day.all %}
				<li><a href="/period_day/{{ d.id }}">{{ d }}</a></li>
			{% endfor %}
			</ul>
		{% else %}
		No days defined for this period.
		{% endif %}
		</td></tr>
		<tr><th>Offerings</th><td>
		{% if item.offering_set.all %}
			<ul class="items">
			{% for o in item.offering_set.all %}
				<li><a href="/offering/{{ o.id }}">{{ o }}</a></li>
			{% endfor %}
			</ul>
		{% else %}
		No courses scheduled for this period.
		{% endif %}
		</td></tr>
		<tr><th>Courses</th><td>
		{% if item.offering_set.all %}
		<ul class="items">
		    {% for o in item.offering_set.all %}
		      <li><a href="/course/{{ o.course.id }}">{{ o.course }}</a></li>
		    {% endfor %}
		</ul>
		{% endif %}
		</td></tr>
		<tr><th>ASP</th><td><pre>{{ item.asp }}</pre></td></tr>
	</table>
{% endblock %}